export const state = {
    activeDevice: {},
    activeDeviceDetails: {},
    activeDeviceSettings: {},
    activeDeviceValidations: [],
    activeRoomName: '',
    builds: [],
    authTokens: [],
    currentBuild: {},
    currentBuildDevices: [],
    currentBuildOrganizations: [],
    currentBuildRacks: [],
    currentBuildUsers: [],
    currentUser: {},
    datacenterRooms: [],
    devices: [],
    forcePasswordChange: false,
    globalWorkspaceId: '',
    hardwareProducts: [],
    highlightDeviceId: '',
    invalidCredentials: false,
    organizations: [],
    rackLayout: {},
    rackRooms: {},
    racks: [],
    showDeviceInRack: false,
    userAuthTokens: [],
    userOrganizations: [],
    users: [],
    validations: [],
};

export default {
    state,
};
