export const initialState = () => {
    return {
        activeDevice: {},
        activeDeviceDetails: {},
        activeDeviceSettings: {},
        activeDeviceValidations: [],
        activeRoomName: '',
        builds: [],
        authTokens: [],
        currentBuild: {},
        currentBuildDevices: [],
        currentBuildOrganizations: [],
        currentBuildRacks: [],
        currentBuildUsers: [],
        currentDataCenter: {},
        currentDataCenterRack: {},
        currentDataCenterRoom: {},
        currentUser: {},
        dataCenters: [],
        datacenterRooms: [],
        devices: [],
        forcePasswordChange: false,
        hardwareProducts: [],
        highlightDeviceId: '',
        invalidCredentials: false,
        organizations: [],
        rackLayout: {},
        rackRooms: {},
        racks: [],
        showDeviceInRack: false,
        userAuthTokens: [],
        userOrganizations: [],
        users: [],
        validations: [],
    };
};

export const state = {
    activeDevice: {},
    activeDeviceDetails: {},
    activeDeviceSettings: {},
    activeDeviceValidations: [],
    activeRoomName: '',
    builds: [],
    authTokens: [],
    currentBuild: {},
    currentBuildDevices: [],
    currentBuildOrganizations: [],
    currentBuildRacks: [],
    currentBuildUsers: [],
    currentDataCenter: {},
    currentDataCenterRack: {},
    currentDataCenterRoom: {},
    currentUser: {},
    dataCenters: [],
    datacenterRooms: [],
    devices: [],
    forcePasswordChange: false,
    hardwareProducts: [],
    highlightDeviceId: '',
    invalidCredentials: false,
    organizations: [],
    rackLayout: {},
    rackRooms: {},
    racks: [],
    showDeviceInRack: false,
    userAuthTokens: [],
    userOrganizations: [],
    users: [],
    validations: [],
};

export default {
    initialState,
    state,
};
